platform :ios, '7.0'

# CocoaPods官方地址
source 'https://github.com/CocoaPods/Specs.git'
# 私有仓库地址
source 'https://git.coding.net/LiuXiaoZhuang/UserCenterModuleSpec.git'
source 'https://git.coding.net/LiuXiaoZhuang/HomePageModuleSpec.git'


target 'MainProject' do
    # 第三方库
    pod 'Masonry'
    pod 'MGJRouter'
    
    # 私有仓库
    pod 'UserCenterModule', '~> 1.2'
    pod 'HomePageModule',   '~> 1.1'
end
